name: Keep Site Alive
on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  schedule:
    - cron: "0 12 * * *"  # Daily at 12:00 UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Git
        run: |
          git config --global user.name "sd9616"
          git config --global user.email "sd96@rice.edu"
          git pull
          
          # Make empty commit
          git commit --allow-empty -m "Keep alive: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          
          git push
